### ISSUE TITLE
Explain promises and async/await? 

### ISSUE THREAD

**Issue by lorensr** [apollographql/core-docs#134]
Some people (eg those coming from Meteor fiberland) won't be familiar with either. I don't see any examples of resolvers in the docs that use callbacks – they all return something directly. Can you use callbacks? And either way, maybe show an example of promiseifying a node lib that only provides callbacks? Eg redis w/ bluebird https://www.npmjs.com/package/redis#promises

**Comment by stubailo** [comment]
I'm not sure that we want to get in the business of teaching people about promises - there are probably a lot of better places on the internet to learn about that. Perhaps we can just link to a good resource about it?

**Comment by lorensr** [comment]
Maybe something like this, with assumed intro teaching elsewhere, and simple examples?

We recommend using [or you can only use] [Promises](https://www.promisejs.org/) or async/await with your resolvers. Here is a good [overview slide deck](http://rossboucher.com/await/#/) of the two options. For instance with promises:

```js
import rp from 'request-promise';

const resolvers = {
  User: {
    fortune {
      return rp('http://fortunecookieapi.com/v1/cookie')
        .then(JSON.parse)
        .then((res) => res[0].fortune.message);
    }
  }
};
```

or with async/await:

```js
import rp from 'request-promise';

const resolvers = {
  User: {
    async fortune {
      const responseString = await rp('http://fortunecookieapi.com/v1/cookie');
      const response = JSON.parse(responseString);
      return response[0].fortune.message;
    }
  }
};
```

In the above examples, calling `rp` returns a promise, because that's how the [`request-promise`](https://www.npmjs.com/package/request-promise) npm library works. When using an npm library that only has functions with callbacks (like [`redis`](https://www.npmjs.com/package/redis#promises)), you can create versions of the functions that instead return promises using the [`bluebird`](http://bluebirdjs.com/docs/getting-started.html) library:

```js
import redis from 'redis';
import bluebird from 'bluebird';

bluebird.promisifyAll(redis.RedisClient.prototype);
bluebird.promisifyAll(redis.Multi.prototype);

const client = redis.createClient();

const resolvers = {
  Query: {
    async publicFeed() {
      const feed = await client.lrangeAsync('public_feed', 0, -1);
      return feed.map(JSON.parse);
    }
  }
};
```

**Comment by helfer** [comment]
I agree with @stubailo on this one. What I think would be a good idea is to provide a link to a good explanation of promises and async/await. What do you think @lorensr ?

**Comment by lorensr** [comment]
I think the brief examples [above](https://github.com/apollostack/docs/issues/134#issuecomment-232167686) would be a helpful, in addition to the links (I included the best I found above). With links to that example section from other possible entry-point sections that use promises/async/await.

**Comment by helfer** [comment]
Actually, yeah, I think I'm convinced. Where in the docs would you put it?

**Comment by lorensr** [comment]
Yay :) Doesn't properly fit in any of the TOC categories. The examples are server, so could go after GraphiQL in the `Apollo Server` section. Could also go at end of `Client Core` or `GraphQL Tools`.

Links:

"a promise"
http://docs.apollostack.com/apollo-client/queries.html
http://docs.apollostack.com/apollo-client/mutations.html
http://docs.apollostack.com/apollo-client/react.html
http://docs.apollostack.com/apollo-server/setup.html

"the Promise"
http://docs.apollostack.com/apollo-client/angular2.html

Meteor article uses async, I'll make the link for that.

For this:

http://docs.apollostack.com/graphql-tools/resolvers.html

maybe add a note after the first example that `Author.find` returns [a promise]

And we should make a note about async/await on the client – either how to use it or that it's not supported by browsers.

**Comment by helfer** [comment]
I think it fits best in the graphql-tools docs, since it's talking about
resolvers.

**Comment by stubailo** [comment]
Going to close this for now unless someone wants to do it. I haven't personally encountered a lot of confusion around promises.
