### ISSUE TITLE
Document enum usage

### ISSUE THREAD

**Issue by ephemer** [apollographql/core-docs#178]
I'm just starting out with Apollo and GraphQL and what I'd like to do is put an enum in my Schema - I can't find any good info about how to do it. The advantage of Apollo seems to be that it's easier to get into than a reference implementation of GraphQL (correct me if I'm wrong) and I think good docs will drive adoption of Apollo above other implementations.

Making an enum was actually a lot easier using the plain JS syntax:

```
// from http://graphql.org/docs/api-reference-type-system/#graphqlenumtype
var RGBType = new GraphQLEnumType({
  name: 'RGB',
  values: {
    RED: { value: 0 },
    GREEN: { value: 1 },
    BLUE: { value: 2 }
  }
});
```

But I couldn't find how to combine this with the template string syntax so I gave up and tried to do it this way:

```
  enum RGBType {
    RED
    GREEN
    BLUE
  }
```

But I can't seem to define any values in that way directly. So I tried to put it in the resolvers but it ends up looking like a mess:

```
    # in my schema:
    type SomeOtherQueryObject {
        color: RGBType!
    }
```

In resolvers:

```
    SomeOtherObject: {
        colour({ level }) {
            switch (level) {
                case 0: return 'RED';
                case 1: return 'GREEN';
                case 2: return 'BLUE';
            }
        }
    },

    RGBType: { // is this even necessary?
        __parseValue (value) {
            // when is this called?
        },
        __serialize(value) {
            // when running a query to get data to the client
            switch (value) {
                case 'RED': return 0;
                case 'GREEN': return 1;
                case 'BLUE': return 2;
            }
        },
        __parseLiteral (ast) {
            // ??
        },
    },
```

Note that the query will fail without a specific resolver on `SomeOtherObject`, which seems unexpected. I thought it'd suffice to just resolve RGBType, but no dice. Ideally I'd like my string labels to show up in GraphiQL (maybe impossible) and for the client to receive the integer raw values. Maybe there's an easier way.

I don't expect a comprehensive answer here and I may figure this out myself (at which point I'll comment here), but a quick confirmation about whether this kind of documentation is planned would be appreciated.

**Comment by helfer** [comment]
Yeah, enums are one of the weak spots in the schema language, because you can't define the value of the enum (it's implicit). I think there would be a way to improve on that, if graphql-js was extended to allow the following:
```
enum RGBType {
  RED: 1
  GREEN: 2
  BLUE: 3
}
```
It might be worth opening an issue on graphql-js, or even making a PR to extend the parser and AST to support it.

I don't think I'll write any documentation for how to do enums at the moment (no time), but if you figure something out that works well, it would be great if you could make a PR!

**Comment by ephemer** [comment]
Thanks, two quick Qs:

1. do you know if it's possible to show something in GraphiQL that's different to the data the client receives? I would understand if this is not the case, by design.

2. Do you know if it's possible to mix and match JS scheme definitions with the template strings? That would be a sufficient workaround for the enum issue for now. I played around with it and couldn't get it to work in any obvious way.

**Comment by helfer** [comment]
@ephemer 

1. I don't think so, at least not without modifying your server and/or GraphiQL. You'll just get the response to the query. If the client sends the same query and it gets executed with the same context, you'll get the same result.

2. In theory yes, but in practice this is a bit tricky at the moment, because the schema gets generated in one go, so you need to have all the types available at that moment. The most straightforward way to enable your use case would probably be to modify graphql-tools in such a way that enum values can be provided in the resolvers object that gets passed to `makeExecutableSchema`. I can help you figure it out, if you'd be willing to make a PR.

**Comment by ephemer** [comment]
@helfer 2. seems like the way to go for the short-medium term. I've kinda given up on enums though for now because I can't see any good use for them in our case.

We have a "difficulty level" stored as an Int in the Db and I wanted to indicate that it only has four possible values (for now) using an enum, but for us using the int is fine. I'll revisit this if we try out enums again

**Comment by gjuchault** [comment]
Hi,

As I didn't know where to go, I created this issue https://github.com/graphql/graphql-js/issues/525 that is related to this comment https://github.com/apollostack/core-docs/issues/178#issuecomment-242163519

**Comment by scf4** [comment]
Can we still not use Enums at all if we use the shorthand syntax?

**Comment by helfer** [comment]
@scf4 enums are supported in graphql-tools now!

**Comment by gjuchault** [comment]
@helfer But how can we put custom values ?

**Comment by ericclemmons** [comment]
Can you link the relevant commit for enum support?

**Comment by helfer** [comment]
Oh, I think my brain must have been sleeping when I wrote this earlier. I was thinking about support for custom scalars, not enums. Sorry!

**Comment by nareshbhatia** [comment]
As far as I can tell, enums are implemented as strings, but I could not find any documentation of that. I am able to send enums as strings in mutation variable and receive them as strings in responses. I also see a PR to add enum support that was merged: https://github.com/apollographql/apollo-client/pull/788. Can someone please clarify if we can at least rely on enums being strings, even if this does not conform to the GraphQL spec?

**Comment by jedwards1211** [comment]
@nareshbhatia "implemented as strings" could confuse people.  While (quoted) strings are used to represent enum values in JSON (for variables and query responses), in GraphQL queries the enum values must not be in quotes:

```graphql
query {
  Pets(type: DOG) {
    name
  }
```

```graphql
query ($petType: PetType) {
  Pets(type: $type) {
    name
  }
}
```
Variables:
```json
{
  "petType": "DOG"
}
```
```

**Comment by stubailo** [comment]
Hmm. We haven't documented this anywhere since it's not really Apollo Client specific - it's exactly the same as if you were to send an HTTP request with `fetch` or similar. So it does conform to the GraphQL spec and general transport stuff.

If someone has ideas for a docs PR, send them along!
