### ISSUE TITLE
Check there's nothing in the old apollo-client page we want that we are missing

### ISSUE THREAD

**Issue by tmeasday** [apollographql/core-docs#189]
http://docs.apollostack.com/apollo-client/index.html

Currently has:
1. Installing -- do we want this in core docs?
2. Initializing -- I think this is best served with just the API doc for the constructor
3. gql query strings -- where should this go?
4. Network Interfaces -- this has moved to "Network Layer"
5. Store hydration -- I think this can live in the guides
6. Change log -- not sure where we want this

**Comment by helfer** [comment]
I think we've got it all covered, but I'm not sure if we found the right place to put all the pieces. For example, I wouldn't expect to find the Apollo Client examples under core JS. Maybe we should split this up into React and Angular examples, and then link those in the respective subsections (if we're not doing that already)
