### ISSUE TITLE
Add reference and docs to eslint-plugin-graphql

### ISSUE THREAD

**Issue by tonyxiao** [apollographql/core-docs#195]
It's one of the best development time features of GraphQL and is an amazing pleasure to use. I would not have discovered it had I note been active on github issues. We should add / prominently highlight it in apollo client docs.

**Comment by stubailo** [comment]
Good idea! I think this would go in the "tools" section.

**Comment by stubailo** [comment]
https://github.com/apollostack/tools-docs

Mind opening a PR there to add it?
