### ISSUE TITLE
Phoenix channels networkInterface

### ISSUE THREAD

**Issue by vic** [apollographql/core-docs#238]
Hello,

I've just published [apollo-phoenix-websocket](https://github.com/vic/apollo-phoenix-websocket), a custom Apollo networkInterface for sending queries via [Phoenix Channels](http://www.phoenixframework.org/docs/channels).

Do you people think it convenient to link to it somewhere in the docs? I could provide a PR if you are ok with this.

**Comment by stubailo** [comment]
This is exciting but I'm not quite sure where it would go. Right now the closest thing we have is this section with integrations: http://dev.apollodata.com/core/meteor.html

But those are pretty hard to find. Perhaps it would be nice to have a list of companion packages somewhere, got any ideas?

**Comment by vic** [comment]
Oh sure, I could write a similar "Phoenix" section (like the meteor one) if you people are interested. I'm currently using [Absinthe](http://absinthe-graphql.org/) as it's the fastest moving graphql library  in Elixir land. Also there is [many](https://elixirforum.com/t/phoenix-graphql-tutorial-with-absinthe/2644) [interest](https://elixirforum.com/t/phoenix-graphql-tutorial-with-absinthe-add-crud-using-mutations/2729) in the [community](https://elixirforum.com/t/phoenix-graphql-tutorial-with-absinthe-authentication-with-guardian/2766), as Elixir/erlang people are already familiar with distributed programming, I'd say most of us are curious of using [gql subscriptions](https://github.com/absinthe-graphql/absinthe/issues/156#issuecomment-270749141) to build our real-time stuff.

**Comment by stubailo** [comment]
Yeah, actually I think presenting it as information about how to integrate with Phoenix would be really cool. Feel free to send a PR with a new page!

**Comment by helfer** [comment]
I'm going to close this since it's been a while. If you're still interested, please send a PR @vic !

**Comment by helfer** [comment]
I'm going to close this since it's been a while. If you're still interested, please send us a PR @vic!
