### ISSUE TITLE
fragments doc: createFragment is no longer defined

### ISSUE THREAD

**Issue by crucialfelix** [apollographql/core-docs#245]
This page seems to be out of date:

https://github.com/apollographql/core-docs/blob/master/source/fragments.md
http://dev.apollodata.com/core/fragments.html

apollo-client: 0.8.1

**Comment by helfer** [comment]
Thanks @crucialfelix! This seems to be an issue with hexo not removing files that no longer exist in the repo. I don't think we still have any links to it, but if you find one, please send us a PR that removes it.
