### ISSUE TITLE
Add documentation about Apollo Client Devtools

### ISSUE THREAD

**Issue by nandito** [apollographql/core-docs#246]
http://dev.apollodata.com/core/devtools.html

The documentation only mentions the Redux DevTools in the Technical Documentation > Developer tools section.

I think Apollo Client Devtools should be mentioned there, too.

**Comment by stubailo** [comment]
I agree! There are tons of places we should mention it, including the React and Angular docs sites as well. You can get screenshots and info from here: https://dev-blog.apollodata.com/apollo-client-developer-tools-ff89181ebcf#.ji4pn1g4k

Would love to see a PR for this in the spirit of contributor week!

**Comment by nandito** [comment]
I think this is done #247
