### ISSUE TITLE
Build broken due to WeakMap typings

### ISSUE THREAD

**Issue by helfer** [apollographql/core-docs#277]
```
Using TypeScript 2.2.2 from /home/ubuntu/core-docs/node_modules/typedoc/node_modules/typescript/lib
Error: /home/ubuntu/core-docs/code/node_modules/@types/lodash/index.d.ts(19586)
 All declarations of 'WeakMap' must have identical type parameters.
```

Not sure how to fix this right now. In the code this isn't a problem, but for some reason it becomes a problem when typedoc is trying to generate the typings. 🤔 
I could add `skipLibCheck: true`, but that would require forking typedoc, which I think would be just making the problem worse in the long term.

I think this happened when some dependency was updated, but I'm not sure which one it was, and it's really hard to figure out after the fact.

**Comment by dotansimha** [comment]
@helfer Updating the git-submodule (`./code`) to the latest works great :)
