### ISSUE TITLE
Document types consumption

### ISSUE THREAD

**Issue by mquandalle** [apollographql/core-docs#44]
As the apollo-client codebase is fully typed, it would be great to document how a user of this library willing to use the TS language should import apollo-client to benefit from the type it exports. I’m unfortunately not sure how the Apollo types should be bundled into the NPM package and I’m not even sure their is a consensus on the recommended way. Any idea?

**Comment by helfer** [comment]
We still don't have this (except for a few lines of documentation in apollo server), and it might be something that's useful for all of our repos. If someone wants to give it a go, I'd be happy to merge the PRs.

**Comment by mquandalle** [comment]
Typings are now referenced in apollo-client `package.json` so types should work automatically for Typescript users.
