### ISSUE TITLE
Move out auth docs from meteor integration

### ISSUE THREAD

**Issue by stubailo** [apollographql/core-docs#58]
http://docs.apollostack.com/apollo-client/meteor.html#Getting-the-current-user

Also, make it not Meteor specific!

**Comment by queso** [comment]
Would it make sense to add more examples as well? Like maybe using passport?

**Comment by stubailo** [comment]
Yes please! I think @helfer already built an example with passport, perhaps he can post a link here.

**Comment by helfer** [comment]
I already wrote a blog post about this, so I will add some information about auth with Passport.js in a new section and also move the part about meteor auth over there.

**Comment by helfer** [comment]
@queso: Here's the link to the post I wrote: https://medium.com/apollo-stack/a-guide-to-authentication-in-graphql-e002a4039d1

If you want to work on the PR for this issue, that would be cool!
