### ISSUE TITLE
Document server-side rendering and store hydration in a new page

### ISSUE THREAD

**Issue by stubailo** [apollographql/core-docs#60]
It would be great to have those in the main table of contents, since that's one of the primary questions people will have - does it support SSR/hydration. Having it be React-specific is probably fine.

@jbaxleyiii, sounds like you have this figured out already?

**Comment by wizardzloy** [comment]
I've started working on SSR example with `react-router`, but figured out that it is not that straightforward to actually build the complete GraphQL query graph on the server and render the app once all the data is fetched. I believe we should somehow enhance the API of `react-apollo` to support this feature, what do you think?
