### ISSUE TITLE
Better document how to use network interface middleware to set auth token

### ISSUE THREAD

**Issue by stubailo** [apollographql/core-docs#83]
Right now this is the only thing we have: http://docs.apollostack.com/apollo-client/meteor.html#Using-with-Meteor-Accounts

**Comment by stubailo** [comment]
Probably the best thing to do about be to add something here: http://docs.apollostack.com/apollo-client/index.html#createNetworkInterface

Probably under a new heading called "Network interface" which can talk about `createNetworkInterface` and how middlewares work.

The code for middleware is here: https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts

In particular, here's the middleware interface, and an example middleware: https://github.com/apollostack/apollo-client/blob/master/src/middleware.ts I didn't realize it, but I don't think we actually use it or even export `AuthTokenHeaderMiddleware`, so we should delete that code soon. Creating a custom middleware to set the token on a header is pretty simple IMO that we don't need a class just to store the login token.

**Comment by czbaker** [comment]
I wrote a PR that handles this specific issue, though it doesn't mention authentication headers specifically.

It could be modified to mention that though.

**Comment by helfer** [comment]
Just for reference, the PR in question is #95
