### ISSUE TITLE
Document plugging into query augmentation

### ISSUE THREAD

**Issue by stubailo** [apollographql/core-docs#88]
The work done for this issue:

https://github.com/apollostack/apollo-client/issues/230

**Comment by jole78** [comment]
how is work progressing on this? I would like to add 'id' to all my queries and I'm not quite understanding how that can be done.
I'll be happy to document it afterwards in PR if anyone could give me some tips on how to get started.

Thanks :)

**Comment by helfer** [comment]
@jole78 this is no longer a feature we support, but you could copy the code that's still in Apollo Client and use it to transform the queries before you pass them in.
